pip install tensorflow
pip install kafka-python
pip install cassandra-driver
pip install flask
pip install flask-cassandra
pip install gunicorn
pip install gevent
pip install tqdm
pip install ipdb
pip install dash
pip install dash_core_components
pip install dash_html_components
